-- show full description 
INFORMATION_SCHEMA.COLUMNS
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'first_table';
-- WHERE  TABLE_SCHEMA = 'hbtn_0c_0' DB PASSED IN COMMAND